spring:
  application:
    name: HELLO-USER-SERV



eureka:
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
  instance:
    prefer-ip-address: 'true'
